version: '3.8'

services:
  needadrop:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # Persistent storage for database
      - needadrop_data:/app/data
      # Persistent storage for uploads
      - needadrop_uploads:/app/uploads
    environment:
      - RUST_LOG=info
      - DATABASE_URL=sqlite:///app/data/needadrop.db
      - UPLOAD_DIR=/app/uploads
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Security constraints
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

volumes:
  needadrop_data:
    driver: local
  needadrop_uploads:
    driver: local
