name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  rust-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo build
        uses: actions/cache@v4
        with:
          path: target/
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}-
            ${{ runner.os }}-cargo-build-

      - name: Cache Cargo tools
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/
          key: ${{ runner.os }}-cargo-tools-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-tools-

      - name: Install audit tools
        run: |
          if ! command -v cargo-audit &> /dev/null; then
            echo "Installing cargo-audit..."
            cargo install cargo-audit
          else
            echo "cargo-audit already installed"
          fi
          if ! command -v cargo-outdated &> /dev/null; then
            echo "Installing cargo-outdated..."
            cargo install cargo-outdated
          else
            echo "cargo-outdated already installed"
          fi

      - name: Run rustfmt
        run: cargo fmt --all -- --check

      - name: Run clippy (with cache optimization)
        run: |
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests (with cache optimization)
        run: |
          cargo test --all

      - name: Run cargo audit
        run: cargo audit

      - name: Check outdated dependencies
        run: cargo outdated
